settings:
  kubeContext: kind-shopping-cart-manager
  maxHistory: 10
  timeout: 6000

namespaces:
  shopping-cart-manager:
    labels:
      managed-by: helmsman

helmRepos:
  bitnami: https://charts.bitnami.com/bitnami

apps:
  shopping-cart-manager:
    enabled: true
    namespace: shopping-cart-manager
    chart: "./shopping-cart-manager"
    version: "0.1.0"
    secretsFiles:
      - ./shopping-cart-manager/secrets.yaml

  mysql:
    enabled: true
    namespace: shopping-cart-manager
    chart: bitnami/mysql
    version: "9.1.0"
    valuesFile: ./mysql/values.yaml
    wait: true
    secretsFiles:
      - ./mysql/secrets.yaml

  redis:
    enabled: true
    chart: bitnami/redis
    version: "17.1.0"
    valuesFile: ./redis/values.yaml
    namespace: shopping-cart-manager
    wait: true
    secretsFiles:
      - ./redis/secrets.yaml
