settings:
  kubeContext: kind-ice-global
  maxHistory: 10
  timeout: 6000

namespaces:
  ice-global:
    labels:
      managed-by: helmsman

apps:
  ice-global:
    name: ice-global
    namespace: ice-global
    chart: "./ice-global"
    enabled: true
    version: "0.1.0"
    secretsFiles:
      - ./ice-global/secrets.yaml
